### ISSUE TITLE
can not connect to db

### ISSUE THREAD

**Issue by iXieYi** [mendix/docker-mendix-buildpack#118]
![image](https://user-images.githubusercontent.com/21982108/112435607-ee1a5c00-8d7f-11eb-82e7-15005de3c7c0.png)
![image](https://user-images.githubusercontent.com/21982108/112435877-481b2180-8d80-11eb-9466-778130415b40.png)

`docker run -it \
  -e ADMIN_PASSWORD=Password1! \
  -e DATABASE_ENDPOINT=postgres://postgres:postgres@localhost:5432/postgresql \
  app`

 ConnectionBus: Opening JDBC connection to Some(localhost:5432) failed with SQLState: 08001 Error code: 0 Message: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections
 
using Navicat to connect db is success
![image](https://user-images.githubusercontent.com/21982108/112436651-ec9d6380-8d80-11eb-8844-bd056547edbe.png)

**Comment by eist76** [comment]
i think this issue is related to docker container context of 'localhost' - which is the container itself and not your laptop/workstation - and not a mendix buildpack issue.
check: https://medium.com/it-dead-inside/docker-containers-and-localhost-cannot-assign-requested-address-6ac7bc0d042b
you might want to try your local IP address instead of 'localhost' for your DB host or add '--network="host"' to your docker run command to give the container full accress to local system services (https://docs.docker.com/engine/reference/run/#network-settings)

**Comment by iXieYi** [comment]
thanks
