### ISSUE TITLE
Update security patch

### ISSUE THREAD

**Issue by peeradech** [mendix/docker-mendix-buildpack#71]
Hi There,

Could you please help to suggest a way to solve security problems (patch)?

![thumbnail_image002](https://user-images.githubusercontent.com/20807891/58145002-d1d8a000-7c7a-11e9-8f77-0e9b53fd2a4d.png)

**Comment by dudk** [comment]
We currently doing a pipeline migration for `mendix/rootfs` image. Because of that image might be missing the most recent (last three weeks) security fixes.
@peeradech you can rebuild rootfs using `Dockerfile.rootfs` file. Then you can use `ROOTFS_IMAGE` build argument to pass the tag of your image.

**Comment by peeradech** [comment]
> We currently doing a pipeline migration for `mendix/rootfs` image. Because of that image might be missing the most recent (last three weeks) security fixes.
> @peeradech you can rebuild rootfs using `Dockerfile.rootfs` file. Then you can use `ROOTFS_IMAGE` build argument to pass the tag of your image.

Thank you so much for reply
